updates

diff --git a/bin/ngseasy_fastqc b/bin/ngseasy_fastqc
--- a/bin/ngseasy_fastqc
+++ b/bin/ngseasy_fastqc
@@ -18,7 +18,7 @@ cat << EOF
   ARGUMENTS:
   -h      Flag: Show this help message
   -c      NGSeasy project and run configureation file
-  -d      project_directory
+  -d      project_directory on local machine
   -t      1 = pre quality trim; 0 = post quality trim
 
   EXAMPLE USAGE:
@@ -53,37 +53,146 @@ config_tsv=""
       esac
   done
 
- 
-
-
 #check config file exists.
 if [ ! -e "${config_tsv}" ] 
 then
-	    echo "ERROR :  ${config_tsv} does not exist "
+	    echo "ERROR :  ${config_tsv} does not exist....exiting "
 	    usage;
 	    exit 1;
 fi
 
 if [ "${fastqc_pre}"!= "1" ] || [ "${fastqc_pre}"!= "0" ]
 then
-	    echo "ERROR : Unexpected argument "
+	    echo "ERROR : Unexpected argument....exiting "
 	    usage;
 	    exit 1;
 fi
 
-# TO ADD: check if volumes container is running and exit if not
-#mounted docker dir
-#script run in docker container and will look for volumes specifef in ngseasy_volumes_contaier
+#Read config file 
+while read -r f1 f2 f3 f4 f5 f6 f7 f8 f9 f10 f11 f12 f13 f14 f15
+do
+
+# set varibales  
+  POJECT_ID=$f1
+  SAMPLE_ID=$f2
+  FASTQ1=$f3
+  FASTQ2=$f4
+  PROJECT_DIR=$f5 
+  DNA_PREP_LIBRARY_ID=$f6
+  NGS_PLATFORM=$f7
+  NGS_TYPE=$f8
+  BED_ANNO=$f9
+  PIPELINE=$f10
+  ALIGNER=$f11
+  VARCALLER=$f12
+  GTMODEGATK=$f13
+  CLEANUP=$f14
+  NCPU=$f15
+
+#check local dir exists
+if [ ! -d "${PROJECT_DIR}/${POJECT_ID}/${SAMPLE_ID}" ]
+then
+  log_ngseasy " Cant Find Project directory. This is then end. Please Stop and check everything is ok "
+  exit 1
+
+else 
+  log_ngseasy " Setting OUTPUT directory [${SOUT}]"
+fi
+
+#check for fastq files exist
+if [ ! -s "${SOUT}/fastq/${FASTQ1}" ] && [ ! -s "${SOUT}/fastq/${FASTQ2}" ]
+then
+  log_ngseasy " Can't Find fastq files [${SOUT}/fastq/${FASTQ1}] and [${SOUT}/fastq/${FASTQ2}] in ${SOUT}/fastq/ "
+  exit 1
+fi
+
+#set new names for copied fastq files
+  rawFASTQ1=`basename ${SOUT}/fastq/${FASTQ1} _1.fq.gz`
+  rawFASTQ2=`basename ${SOUT}/fastq/${FASTQ2} _2.fq.gz`
+    
+log_ngseasy " NGSeasy: Fastq Basename : [$rawFASTQ1] "
+
+#-------------------------------------------------------------------#
+#FASTQC on raw files
+log_ngseasy " NGSeasy: START FASTQC " 
+
+#check if qc'd data alread exists 
+if [ -s "${SOUT}/fastq/${rawFASTQ1}_1.fq_fastqc.zip" ] && [ -s "${SOUT}/fastq/${rawFASTQ2}_2.fq_fastqc.zip" ]
+then
+  log_ngseasy " FastQC Data already exists...skipping"
+else
+fi
+
+#Docker Output Dir: this is the mouned directory set by ngseasy_volumes_container
 DOCKERHOME="/home/pipeman/ngs_projects"
+
+#Logfile
+LOGFILE=${PROJECT_DIR}/${POJECT_ID}/run_logs/${SAMPLE_ID}.${DATE}
+
+#OUTPUT SAMPLE DIR 
+SOUT=${DOCKERHOME}/${PROJECT_DIR}/${POJECT_ID}/${SAMPLE_ID}
+
+# if before trimmomatic
+if [ "${pre_or_post}" == "1" ]
+then
+  log_ngseasy " START: FastQC on raw Fastq files " ${LOGFILE}
 
 #run compbio/ngseasy-fastq
   sudo docker run \
-  -d \
   -P \
-  --name fastqc \
+  --name fastqc.${SAMPLE_ID} \
   --volumes-from volumes_container \
-  -t compbio/ngseasy-fastqc:v0.9 /bin/bash ${DOCKERHOME}/ngs/bin/run_ngseasy_fastqc.sh ${fastqc_pre} ${config_tsv}
+  -t compbio/ngseasy-fastqc:v0.9 /usr/local/pipeline/FastQC/fastqc \
+    --threads ${NCPU} \
+    --extract \
+    --quiet \
+    --dir ${SOUT}/tmp \
+    --rm \
+    --outdir ${SOUT}/fastq \
+    ${SOUT}/fastq/${rawFASTQ1}_1.fq.gz \
+    ${SOUT}/fastq/${rawFASTQ2}_2.fq.gz
+#log 
+  log_ngseasy " END: FastQC on raw Fastq files " 
+fi
 
+if [ "${pre_or_post}" == "0" ]
+then
+# if run after trimmomatic
+# Trimmomatic paired output
+  qcdPeFASTQ1=${SOUT}/fastq/${rawFASTQ1}_1.filtered.fq.gz;
+  qcdPeFASTQ2=${SOUT}/fastq/${rawFASTQ2}_2.filtered.fq.gz;
+# Trimmomatic unpaired ouput
+  qcdSeFASTQ1=${SOUT}/fastq/${rawFASTQ1}_1.unpaired.fq.gz;
+  qcdSeFASTQ2=${SOUT}/fastq/${rawFASTQ2}_2.unpaired.fq.gz;
+   
+#check if fastq files exist
+if [ ! -s ${SOUT}/fastq/${rawFASTQ1}_1.filtered.fq.gz ] && [ ! -s ${SOUT}/fastq/${rawFASTQ2}_2.filtered.fq.gz ]
+then
+  log_ngseasy " Cant'd Find Trimmed Fastq files in ${SOUT}/fastq/ ie [${rawFASTQ1}_1.filtered.fq.gz] or [${rawFASTQ1}_1.unpaired.fq.gz] "
+  exit 1
+fi
+
+  log_ngseasy " START: FastQC on Trimmed Fastq files " 
+
+#run compbio/ngseasy-fastq
+  sudo docker run \
+  -P \
+  --name fastqc.${SAMPLE_ID} \
+  --volumes-from volumes_container \
+  -t compbio/ngseasy-fastqc:v0.9 /usr/local/pipeline/FastQC/fastqc \
+    --threads ${NCPU} \
+    --extract \
+    --quiet \
+    --dir ${SOUT}/tmp \
+    --rm \
+    --outdir ${SOUT}/fastq \
+    ${SOUT}/fastq/${rawFASTQ1}_1.fq.gz \
+    ${SOUT}/fastq/${rawFASTQ2}_2.fq.gz
+#log
+  log_ngseasy " END: FastQC on Trimmed Fastq files " 
+fi
+
+done < ${config_tsv}
 
 }
 
