started bin/ngseasy_alignment_qc

diff --git a/bin/ngseasy_alignment_qc b/bin/ngseasy_alignment_qc
--- a/bin/ngseasy_alignment_qc
+++ b/bin/ngseasy_alignment_qc
@@ -1,20 +1,230 @@
+#!/bin/bash -x
+# Collection of NGSeasy Functions
+# Stephen Newhouse <stephen.j.newhouse@gmail.com>
+# Version 0.9.0
 
+##--------------------------------------------------##
+## NGS alignment_summary_metrics
+##--------------------------------------------------##
 
+#usage printing func
+usage() {
+cat << EOF
+  This script sets up the NGSeasy docker Alignmnet Summary Metrics
+  See NGSEasy containerized instructions.
 
+  ARGUMENTS:
+  -h      Flag: Show this help message
+  -c      NGSeasy project and run configureation file
+  -d      NGSeasy project directory
 
- # FindCoveredIntervals: these are used in GATK Calling to help speed things up
+  EXAMPLE USAGE:
+    
+    ngseasy_alignment_qc -c config.file.tsv -d project_directory
 
-echo " NGSeasy: START FindCoveredIntervals " `date`  
-if [ ! -s ${SOUT}/reports/${BAM_PREFIX}.CoveredIntervals_x4.list ]
+EOF
+}
+
+# to be run on recal and filtered data if available
+# if no gatl cleaning then dupemk and filtered is the final data set 
+
+#get options for command line args
+  while  getopts "hc:d:" opt
+  do
+
+      case ${opt} in
+	  h)
+	  usage #print help
+	  exit 0
+	  ;;
+	  
+	  c)
+	  config_tsv=${OPTARG}
+	  ;;
+
+	  d)
+	  project_directory=${OPTARG}
+	  ;; 
+      esac
+  done
+
+# Check options passed in.
+    if test -z "$2"
+    then
+	usage
+	exit 1
+    fi  
+  
+#check config file exists.
+  if [ ! -e "${config_tsv}" ] 
+  then
+	      echo "ERROR :  ${config_tsv} does not exist....exiting "
+	      usage;
+	      exit 1;
+  fi
+
+#check directory exists.
+  if [ ! -d "${project_directory}" ]
+    then
+      echo "ERROR : project_directory ${project_directory} does not exist "
+      usage;
+      exit 1;
+  fi
+
+#---------------------------------------------------------------------------------#
+
+#Read config file 
+while read -r f1 f2 f3 f4 f5 f6 f7 f8 f9 f10 f11 f12 f13 f14 f15
+do
+# set varibales  
+  DATE=`date +"%d%m%y"`
+  POJECT_ID=$f1
+  SAMPLE_ID=$f2
+  FASTQ1=$f3
+  FASTQ2=$f4
+  PROJECT_DIR=$f5 
+  DNA_PREP_LIBRARY_ID=$f6
+  NGS_PLATFORM=$f7
+  NGS_TYPE=$f8
+  BED_ANNO=$f9
+  PIPELINE=$f10
+  ALIGNER=$f11
+  VARCALLER=$f12
+  GTMODEGATK=$f13
+  CLEANUP=$f14
+  NCPU=$f15
+
+#Logfile 
+LOGFILE=${PROJECT_DIR}/${POJECT_ID}/run_logs/${SAMPLE_ID}.${DATE}
+
+#OUTPUT SAMPLE DIR 
+SOUT=${PROJECT_DIR}/${POJECT_ID}/${SAMPLE_ID}
+
+#------------------------Container I/O--------------------------------#
+#run compbio/ngseasy-fastq
+#Docker Output Dir: this is the mouned directory set by ngseasy_volumes_container
+DOCKERHOME="/home/pipeman/ngs_projects"
+
+#Docker OUTPUT SAMPLE DIR 
+SOUTDocker=${DOCKERHOME}/${POJECT_ID}/${SAMPLE_ID}
+
+#bamprefix
+BAM_PREFIX=${SAMPLE_ID}.${NGS_TYPE}.${NGS_PLATFORM}.${ALIGNER}
+
+#known indels and SNPs
+KNOWN_INDELS=/home/pipeman/gatk_resources/Mills_and_1000G_gold_standard.indels.b37.vcf
+KNOWN_SNPS_1000G=/home/pipeman/gatk_resources/1000G_phase1.snps.high_confidence.b37.vcf
+KNOWN_SNPS_OMNI=/home/pipeman/gatk_resources/1000G_omni2.5.b37.vcf
+KNOWN_SNPS_b138=/home/pipeman/gatk_resources/dbsnp_138.b37.vcf
+
+#--------Check BAM Files Exists and Exit if Not----------------------------#
+
+# test for recal or dupemk
+# some flexibility needed here - if GATK not run then use dupemk.bam file
+# files contain ALL reads. Some QC may need filtered.bam
+
+if [ -s "${SOUT}/alignments/${BAM_PREFIX}.recal.bam" ]
 then
-echo " NGSeasy: Finding Covered Intervals : minimum coverage of 4 " `date`
-  java -Xmx6g -Djava.io.tmpdir=${SOUT}/tmp -jar /usr/local/pipeline/GenomeAnalysisTK-3.2-2/GenomeAnalysisTK.jar -T FindCoveredIntervals -R ${REFGenomes}/human_g1k_v37.fasta \
-  -I ${SOUT}/alignments/${BAM_PREFIX}.dupemk.bam  \
-  -o ${SOUT}/reports/${BAM_PREFIX}.CoveredIntervals_x4.list \
-  --coverage_threshold 4;
+
+  bam_file='${SOUTDocker}/alignments/${BAM_PREFIX}.recal.bam'
+  qc_file='${SOUTDocker}/reports/${BAM_PREFIX}.recal.bam'
+  
+  logger_ngseasy "Using Recalibrated BAM File" ${LOGFILE}
+  echo "Using Recalibrated BAM File" 
+
+elif [ -s "${SOUT}/alignments/${BAM_PREFIX}.dupemk.bam" ]
+
+  bam_file='${SOUTDocker}/alignments/${BAM_PREFIX}.dupemk.bam'
+  qc_file='${SOUTDocker}/reports/${BAM_PREFIX}.dupemk.bam'
+  
+  logger_ngseasy "Using Duplicate Marked BAM File" ${LOGFILE}
+  echo "Using Duplicate Marked BAM File" 
+  
+else
+  
+  logger_ngseasy "ERROR : Cant Find recal.bam or dupemk.bam files. Exiting...."  ${LOGFILE}
+  echo "ERROR : Cant Find recal.bam or dupemk.bam files. Exiting...."
+  usage()
+  exit 1
 fi
+
+
+#---------Does filtered bam exits, if not then generate it----------------------#
+
+if [ ! -s "${SOUT}/alignments/${BAM_PREFIX}.filtered.bam" ]
+then
+
+  logger_ngseasy " Filtered BAM [${SOUT}/alignments/${BAM_PREFIX}.filtered.bam] Does Not Exist "  ${LOGFILE}
+  logger_ngseasy " START samtools view -bh -q 20 -F 1796 [${SOUTDocker}/alignments/${BAM_PREFIX}.recal.bam]  "  ${LOGFILE}
+
+  sudo docker run \
+  -P \
+  --name samtools_filter_${SAMPLE_ID} \
+  --volumes-from volumes_container \
+  -t compbio/ngseasy-samtools:v0.9 /bin/bash -c \
+  "/usr/local/pipeline/samtools/samtools \
+  view \
+  -b \
+  -h \
+  -q 20 \
+  -F 1796 \
+  ${bam_file} > ${SOUTDocker}/alignments/${BAM_PREFIX}.filtered.bam; 
+  /usr/local/pipeline/samtools/samtools index ${SOUTDocker}/alignments/${BAM_PREFIX}.filtered.bam"
+
+  sudo docker logs samtools_filter_${SAMPLE_ID} >> ${LOGFILE}.log
+  sudo docker rm samtools_filter_${SAMPLE_ID}
+
+  cp -v ${SOUT}/alignments/${BAM_PREFIX}.filtered.bai ${SOUT}/alignments/${BAM_PREFIX}.filtered.bam.bai;
+
+  logger_ngseasy " END samtools view -b -h -q 20 -F 1796 [${SOUTDocker}/alignments/${BAM_PREFIX}.recal.bam]  "  ${LOGFILE}
+
+else
+
+  logger_ngseasy " Filtered BAM [${SOUT}/alignments/${BAM_PREFIX}.filtered.bam] Exists  "  ${LOGFILE}
+fi
+
+
+#--------Begin generating summary metric----------------------------#
+
+# 0 Basic FlatStats
+  logger_ngseasy " START SAMTOOLS FLAGSTATS  "  ${LOGFILE}
+
+  sudo docker run \
+  -P \
+  --name samtools_flagstats_${SAMPLE_ID} \
+  --volumes-from volumes_container \
+  -t compbio/ngseasy-samtools:v0.9 /bin/bash -c "usr/local/pipeline/samtools/samtools flagstats ${bam_file} > ${qc_file}.flagstats"
   
+  sudo docker logs samtools_flagstats_${SAMPLE_ID} >> ${LOGFILE}.log
+  sudo docker rm samtools_flagstats_${SAMPLE_ID}
   
+  logger_ngseasy " END SAMTOOLS FLAGSTATS  "  ${LOGFILE}
+  
+# 1 Convert BAM to BED
+
+# 2 Convert BAM to Merged BED 
+
+# 3 bedtools genomecov 
+
+# 4 CollectMultipleMetrics
+
+# 5 CollectAlignmentSummaryMetrics
+
+# 6 CollectWgsMetrics
+
+# 7 CollectTargetedPcrMetrics
+
+#--------END generating summary metric----------------------------#
+
+# To DO - R scripts to process and make pretty reports and add to database
+
+#------permissions------------#
+chmod -R 777 ${SOUT}/*
+
+done < ${config_tsv}
+
+
+ 
 # BAM to BED
 echo " NGSeasy: START bamtobed " `date`  
 
@@ -77,22 +287,6 @@ then
   awk 'NR>9' ${SOUT}/reports/${BAM_PREFIX}.wgs_coverage > ${SOUT}/reports/${BAM_PREFIX}.wgs_coverage_hist
   sed '8q' ${SOUT}/reports/${BAM_PREFIX}.wgs_coverage > ${SOUT}/reports/${BAM_PREFIX}.wgs_coverage_stats
 
-# FlagStat
-  echo " NGSeasy: FlagStat " `date`
-  
-    java -Xmx6g -Djava.io.tmpdir=${SOUT}/tmp -jar /usr/local/pipeline/GenomeAnalysisTK-3.2-2/GenomeAnalysisTK.jar -T FlagStat -R ${REFGenomes}/human_g1k_v37.fasta \
-    -I ${SOUT}/alignments/${BAM_PREFIX}.bam  \
-    -o ${SOUT}/reports/${BAM_PREFIX}.FlagStat;
-    
-else
-    echo " NGSeasy: Post Alignmnet QC Already Run " `date` 
-fi
-
-echo ""
-echo "................................................"
-echo " NGSeasy: END Post Alignmnet QC " `date`
-echo "................................................"
-echo ""
 
 ## Depending in NGS type Run PicardTools CollectTargetedPcrMetrics
 ## NB This is rough and ready quicl fix to get coverage ver genome bins, annotated exomes and targetd sequene files
@@ -174,3 +368,16 @@ echo "................................................"
 echo " NGSeasy: END Post Alignmnet Coverage Calculations " `date`
 echo "................................................"
 echo ""
+
+# FindCoveredIntervals: these are used in GATK Calling to help speed things up
+
+echo " NGSeasy: START FindCoveredIntervals " `date`  
+if [ ! -s ${SOUT}/reports/${BAM_PREFIX}.CoveredIntervals_x4.list ]
+then
+echo " NGSeasy: Finding Covered Intervals : minimum coverage of 4 " `date`
+  java -Xmx6g -Djava.io.tmpdir=${SOUT}/tmp -jar /usr/local/pipeline/GenomeAnalysisTK-3.2-2/GenomeAnalysisTK.jar -T FindCoveredIntervals -R ${REFGenomes}/human_g1k_v37.fasta \
+  -I ${SOUT}/alignments/${BAM_PREFIX}.dupemk.bam  \
+  -o ${SOUT}/reports/${BAM_PREFIX}.CoveredIntervals_x4.list \
+  --coverage_threshold 4;
+fi
+  
